### ISSUE TITLE
[EasyTag] Rating row in QuickEdit tab

### ISSUE THREAD

**Issue by DogmaDragon** [S3L3CT3DLoves/stashPlugins#1]
The rating row is not redundant since ratings were moved out of the edit tab to the general main page and can be updated live without needing to reload the page.

**Comment by S3L3CT3DLoves** [comment]
Thanks for the ping, indeed it might be worth removing the slider now.
I'll give it some thought for the next update, mostly because the slider is a lot easier to use than the half-stars.

**Comment by S3L3CT3DLoves** [comment]
Implemented in v0.13
